# Site settings
title: Travelog
subtitle: "Journal of Matthew Searle"
email: "matthewjsearle@gmail.com"
description: "I'm a chronic sufferer of wanderlust. When not daydreaming about my next trip I'm learning to become a web developer'."
baseurl: ""
url: ""
twitter_username: "MattSNZ"
github_username:  "MattSNZ"
instagram_username: "MattSNZ"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed