# Site settings
title: Learning Log
subtitle: "Journal of Matthew Searle"
email: "matthewjsearle@gmail.com"
description: "A log of my learning journey as I learn to become a web developer."
baseurl: ""
url: ""
twitter_username: "MattSNZ"
github_username:  "MattSNZ"
instagram_username: "MattSNZ"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed